apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-appset
spec:
  generators:
  - list:
      elements:
      - environment: qa
        sourceRepoBranch: staging       
        destUrl: https://kubernetes.default.svc
        destNamespace: qa
      - environment: staging      
        sourceRepoBranch: staging         
        destUrl: https://kubernetes.default.svc
        destNamespace: staging
      - environment: prod
        sourceRepoBranch: HEAD       
        destUrl: https://kubernetes.default.svc
        destNamespace: prod
  template:
    metadata:
      name: '{{environment}}-app1'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/ssijbabu/app1.git'
        targetRevision: {{ sourceRepoBranch }}
        path: ./app-manifest-demo/envs/{{environment}}
        directory:
          recurse: true
      destination:
        server: {{ destUrl }}
        namespace: {{ destNamespace }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true