apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: My Argo CD project
  sourceRepos:
    - 'https://my-git-repository.git'
  destinations:
    - namespace: my-namespace
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'