apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
spec:
  description: My Argo CD project
  sourceRepos:
    - 'https://github.com/ssijbabu/app1.git'
  destinations:
    - namespace: prod
      server: 'https://kubernetes.default.svc'
    - namespace: qa
      server: 'https://10.5.0.110:6443'
    - namespace: staging
      server: 'https://10.5.0.110:6443'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'