apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
spec:
  project: my-project
  source:
    repoURL: 'https://my-git-repository.git'
    targetRevision: HEAD
    path: path/to/your/application
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
