apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook-proj
  namespace: argocd
spec:
  description: Project for guestbook app
  sourceRepos:
    - 'https://github.com/argoproj/argocd-example-apps.git'
  destinations:
    - namespace: prod
      server: 'https://kubernetes.default.svc'
    - namespace: qa
      server: 'https://kubernetes.default.svc'
    - namespace: staging
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'