apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: app1-proj
  source:
    repoURL: 'https://github.com/ssijbabu/app1.git'
    targetRevision: HEAD
    path: ./app-manifest-demo/envs/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
